apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: app-trafficsplit
spec:
  service: app-service
  backends:
  - service: appv1
    weight: 90
  - service: appv2
    weight: 10
