apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: app-trafficsplit
  namespace: linkerd-test
spec:
  service: app
  backends:
  - service: app1
    weight: 90
  - service: app2
    weight: 10
