apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: appv1
  namespace: linkerd-test
spec:
  # ingress reference
  provider: nginx
  ingressRef:
    apiVersion: extensions/v1beta1
    kind: Ingress
    name: appv1-ingress
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appv1
  service:
    # container port
    port: 80
  analysis:
    interval: 1m
    threshold: 10
    iterations: 5
    match:
      # curl -H 'X-Canary: always' http://app.example.com
      - headers:
          x-canary:
            exact: "always"
      # curl -b 'canary=always' http://app.example.com
      - headers:
          cookie:
            exact: "canary"
    # Linkerd Prometheus checks
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 30s